--- #YAML:1.0
name: Gestinanna-POF-Repository
version: 0.04
license: perl
distribution_type: module
requires:
  Algorithm::Diff: 1.15
  Alzabo: 0.82
  Data::Serializer: 0
  Gestinanna::POF: 0.07
recommends:
  DBD::SQLite: 0
build_requires: {}
conflicts: {}
provides:
  Gestinanna::POF::Repository:
    file: lib/Gestinanna/POF/Repository.pm
    version: 0.04
  Gestinanna::POF::Repository::Description:
    file: lib/Gestinanna/POF/Repository/Description.pm
  Gestinanna::POF::Repository::Object:
    file: lib/Gestinanna/POF/Repository/Object.pm
  Gestinanna::POF::Repository::Tag:
    file: lib/Gestinanna/POF/Repository/Tag.pm
generated_by: Module::Build version 0.21
